class QuestionsController < ApplicationController
  def answer
    @query = params[:query]
    @answer = coach_answers #method defined bellow
  end

  def ask
  end

#this will be my answers generated by the coach/ sample answers + time now def
  def coach_answers
    #["Fuck off!", "Sorry I'am busy!", "No time for you!"].sample
    if @query == "What time?"
      return "It's #{Time.now}"
    else
      ["Fuck off!", "Sorry I'am busy!", "No time for you!"].sample
    end
  end
end




